# Generated by Django 4.2.9 on 2024-05-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_myform', '0003_alter_post_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='birth',
        ),
    ]
