# Generated by Django 4.2.10 on 2024-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_myform", "0005_post_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
