# Generated by Django 4.2.9 on 2024-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_myform', '0004_remove_post_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth',
            field=models.IntegerField(default=1960),
        ),
    ]
