# Generated by Django 4.2.9 on 2024-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_myform', '0005_post_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_city', models.CharField(choices=[['TP', 'Taipei'], ['TY', 'Taoyuan'], ['TC', 'Taichung'], ['TN', 'Tainan'], ['KS', 'Kaohsiung'], ['NA', 'Others']], max_length=10)),
                ('user_school', models.BooleanField(default=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_message', models.TextField()),
            ],
        ),
    ]
